theme: minima
title: Montgomery Github Site
author: Montgomery Jackson
descritption: This is Montgomery Jackson's very first Github Site. I am creating this site to further my Software Development skills. Currently it is my goal to learn and understand my code in order to build great sites and challenge myself to continue learning new skills no matter what. 
